_base-dep: &base-dep base >=4.7 && <5

# https://github.com/sol/hpack/issues/303#issuecomment-700905674
_elide-paths:    &elide-paths
  condition:     false
  other-modules: Paths_mattaudesse_com_lib

name:         mattaudesse-com-lib
version:      0.1.0
synopsis:     Matt Audesse's personal website
description:  See README at <https://github.com/mattaudesse/mattaudesse.com#readme>
category:     Website
author:       Matt Audesse
maintainer:   Matt Audesse <matt@mattaudesse.com>
license:      AllRightsReserved
license-file: LICENSE
github:       mattaudesse/mattaudesse.com
homepage:     https://mattaudesse.com
ghc-options:  -Wall

extra-source-files:
  - LICENSE
  - Makefile
  - README.md
  - package.yaml
  - ps/**/*
  - psc-package.json
  - stack.yaml
  - static/**/*

library:
  source-dirs: hs/lib
  when:
    - *elide-paths
  dependencies:
    - *base-dep
    - aeson
    - async
    - bytestring
    - clay
    - conduit
    - http-types
    - mime-mail
    - monad-logger
    - mtl
    - pandoc
    - persistent
    - persistent-sqlite
    - persistent-template
    - resource-pool
    - safe
    - safe-exceptions
    - servant-server
    - shake
    - slick
    - smtp-mail
    - text
    - time
    - validation
    - wai
    - wai-app-static
    - warp
    - yaml

executables:
  mattaudesse-com:
    main:         Main.hs
    source-dirs:  hs/app
    when:
      - *elide-paths
    dependencies:
      - *base-dep
      - mattaudesse-com-lib
      - optparse-applicative
      - unix
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  mattaudesse-com-static:
    main:         BuildStatic.hs
    source-dirs:  hs/build-static
    when:
      - *elide-paths
    dependencies:
      - *base-dep
      - mattaudesse-com-lib
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is BuildStatic

tests:
  spec:
    source-dirs: hs/test
    main:        Spec.hs
    when:
      - *elide-paths
    dependencies:
      - *base-dep
      - mattaudesse-com-lib
      - aeson
      - async
      - bytestring
      - case-insensitive
      - hspec
      - hspec-wai
      - http-types
      - monad-logger
      - mtl
      - neat-interpolation
      - persistent
      - persistent-sqlite
      - servant-server
      - text
      - time
      - wai-extra
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
