resolver: lts-16.26
packages:
  - .

flags:
  HaskellNet-SSL:
    NoUpperBounds: true

extra-deps:
  - slick-1.0.1.1@sha256:bd27d2237126f8883b14c4a1e6c19b6640ed8dae5ba18e9eb8877c1ee23d5c1e,1307

  # HaskellNet
  - git:    https://github.com/jtdaugherty/HaskellNet.git
    commit: 5aa1f3b009253b02c4822005ac59ee208a10a347

  # HaskellNet-SSL
  - git:    https://github.com/mattaudesse/HaskellNet-SSL.git
    commit: 9a7a957f25c7586e9aa9e5202b59f1217380f299
